event system/event system/events/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.EventListView.as_view(), name='events'),
    url(r'^statistics/$', views.EventsStatistics.as_view(), name='events_stats'),
    url(r'^participate/$', views.participate, name='participate'),
    url(r'^get_attendees/$', views.get_attendees, name='get_attendees'),
    url(r'^(?P<pk>\d+)/$', views.EventDetailView.as_view(), name='event'),
    url(r'^(?P<pk>\d+)/edit/$', views.EventUpdateView.as_view(), name='event_edit'),
    url(r'^add/$', views.EventCreateView.as_view(), name='event_create'),
    url(r'^send_notification/$', views.SendNotification.as_view(), name='send_notification'),
]

event system/event system/summits_management/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
	url(r'^$', views.Home.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^events/', include('events.urls', namespace='events')),
    url(r'^accounts/profile/(?P<pk>\d+)/(?P<username>[a-z0-9_-]+)/$', views.UserDetailView.as_view(), name='account_profile'),
    url(r'^accounts/profile/(?P<pk>\d+)/(?P<username>[a-z0-9_-]+)/edit/$', views.UserUpdateView.as_view(), name='account_profile_edit'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^inbox/notifications/', include('notifications.urls', namespace='notifications')),
]

event system/event system/templates/base.html
{% load static %}
{% load account %}
{% load notifications_tags %}
{% notifications_unread as unread_count %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Events | FOSSASIA</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    {% block additional_css %}
    {% endblock additional_css %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">Events | FOSSASIA</a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              {% with user=request.user%}
              {% if user.is_authenticated %}
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">{% user_display user %}&nbsp;<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'account_profile' user.pk user.username %}">Profile</a></li>
                    <li><a href="{% url 'account_logout' %}">Logout</a></li>
                </ul>
              </li>
              {% else %}
                <li><a href="{% url 'account_login' %}">Login</a></li>
              {% endif %}
                <li><a href="{% url 'events:events' %}">View events</a></li>
              {% if user.is_staff %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administraion&nbsp;<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'events:event_create' %}">Add event</a></li>
                    <li><a href="{% url 'events:send_notification' %}">Send notification</a></li>
                    <li><a href="{% url 'events:events_stats' %}">Events statistics</a></li>
                  </ul>
                </li>
              {% endif %}
              {% if request.user.is_authenticated %}
                {% if unread_count %}
                  <li><a href="{% url 'notifications:unread' %}">Messages&nbsp;&nbsp;<span class="badge">{{ unread_count }}</span></a></li>
                {% else %}
                  <li><a href="{% url 'notifications:all' %}">Messages</a></li>
                {% endif %}                
              {% endif %}
            {% endwith %}
          </ul>
          </div><!-- /.navbar-collapse -->
        </div>
        </div><!-- /.container-fluid -->
      </nav>
      <!-- Main Content -->
      <div class="container">
        {% block content %}
          
        {% endblock content %}
      </div>
      <!-- Footer -->
      <footer>
        <div class="container text-center">
          <hr />
          <div class="row">
            <div class="col-lg-12">
              <ul class="nav nav-pills nav-justified">
                <li><a href="/">© 2016 FOSSASIA</a></li>
                <li><a href="#">Terms of Service</a></li>
                <li><a href="#">Privacy</a></li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
      <!-- jQuery -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.js"></script>
      <!-- Bootstrap Core JavaScript -->
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <!-- Custom JavaScript -->
      <script src="{% static 'js/main.js' %}"></script>
      {% block additional_js %}
      {% endblock additional_js %}
    </body>
  </html>