event system/event system/events/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.EventListView.as_view(), name='events'),
    url(r'^statistics/$', views.EventsStatistics.as_view(), name='events_stats'),
    url(r'^participate/$', views.participate, name='participate'),
    url(r'^get_attendees/$', views.get_attendees, name='get_attendees'),
    url(r'^(?P<pk>\d+)/$', views.EventDetailView.as_view(), name='event'),
    url(r'^(?P<pk>\d+)/edit/$', views.EventUpdateView.as_view(), name='event_edit'),
    url(r'^add/$', views.EventCreateView.as_view(), name='event_create'),
    url(r'^send_notification/$', views.SendNotification.as_view(), name='send_notification'),
]

event system/event system/summits_management/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
	url(r'^$', views.Home.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^events/', include('events.urls', namespace='events')),
    url(r'^accounts/profile/(?P<pk>\d+)/(?P<username>[a-z0-9_-]+)/$', views.UserDetailView.as_view(), name='account_profile'),
    url(r'^accounts/profile/(?P<pk>\d+)/(?P<username>[a-z0-9_-]+)/edit/$', views.UserUpdateView.as_view(), name='account_profile_edit'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^inbox/notifications/', include('notifications.urls', namespace='notifications')),
]

event system/event system/events/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.core.urlresolvers import reverse
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from ckeditor.fields import RichTextField

PARTICIPATION_STATUSES = (
    (0, 'No, thanks'),
    (1, 'I may attend'),
    (2, 'I\'ll be there'),
)


class Event(models.Model):
    title = models.CharField(_('title'), max_length=200)
    location = models.CharField(_('location'), max_length=200)
    description = RichTextField()
    organizers = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='organized_events', verbose_name=_('organizers'))
    date = models.DateField(_('event date'))
    date_added = models.DateTimeField(auto_now_add=True)
    participants = models.ManyToManyField(
        settings.AUTH_USER_MODEL, through='Participation', related_name='in_events', verbose_name=_('participants'))

    class Meta:
        verbose_name = "Event"
        verbose_name_plural = "Events"
        ordering = ['-date_added']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('events:event', args=[self.pk])


class Participation(models.Model):
    event = models.ForeignKey(Event, verbose_name=_('event'), related_name='event_participations')
    person = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name=_('person'), related_name='person_participations')
    status = models.PositiveIntegerField(
        _('participation status'), choices=PARTICIPATION_STATUSES)
    date_registered = models.DateTimeField(
        _('date registered'), auto_now_add=True)

    def __str__(self):
        return '{} - {} ({})'.format(self.person, self.event, self.get_status_display())


class Participant(AbstractUser):
    location = models.CharField(_('location'), max_length=200, blank=True)
    website = models.URLField(_('website'), blank=True)
    bdate = models.DateField(_('birthday date'), blank=True, null=True)

    class Meta:
        verbose_name = "Participant"
        verbose_name_plural = "Participants"

    def get_absolute_url(self):
        return reverse('account_profile', args=[self.pk, self.username])

event system/event system/events/forms.py
from django import forms

from ckeditor.widgets import CKEditorWidget

from .models import Event

class NotificationForm(forms.Form):
    verb = forms.CharField(label='Title')
    description = forms.CharField(widget=CKEditorWidget())
    related_events = forms.ModelMultipleChoiceField(queryset=Event.objects.all())

event system/event system/events/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, FormView
from django.views.decorators.http import require_POST, require_GET
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from django.shortcuts import get_object_or_404
from django.db.models import IntegerField, Case, When, Count
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.db import transaction

from braces.views import LoginRequiredMixin, StaffuserRequiredMixin
from notifications.signals import notify

from .models import PARTICIPATION_STATUSES, Event, Participation, Participant
from .forms import NotificationForm


class EventListView(ListView):
    model = Event
    template_name = "events/events.html"
    context_object_name = 'events'
    paginate_by = 10


class EventsStatistics(LoginRequiredMixin, StaffuserRequiredMixin, ListView):
    model = Event
    template_name = "events/events_stats.html"
    context_object_name = 'events'
    paginate_by = 25

    def get_queryset(self):
        queryset = self.model.objects.all()
        queryset = queryset.annotate(
            declined=Count(
                Case(When(event_participations__status=0, then=1),
                     output_field=IntegerField())
            ),
            not_sure=Count(
                Case(When(event_participations__status=1, then=1),
                     output_field=IntegerField())
            ),
            accepted=Count(
                Case(When(event_participations__status=2, then=1),
                     output_field=IntegerField())
            )
        )
        return queryset


class EventDetailView(DetailView):
    model = Event
    template_name = "events/event.html"
    context_object_name = 'event'

    def get_context_data(self, **kwargs):
        context = super(EventDetailView, self).get_context_data(**kwargs)
        context['participation_statuses'] = PARTICIPATION_STATUSES
        if self.request.user.is_authenticated():
            try:
                context['user_status'] = Participation.objects.get(
                    person=self.request.user, event=self.object).status
            except Participation.DoesNotExist:
                pass
        return context


class EventCreateView(LoginRequiredMixin, StaffuserRequiredMixin, CreateView):
    model = Event
    template_name = "events/event_create.html"
    fields = ['title', 'description', 'date', 'organizers']


class EventUpdateView(LoginRequiredMixin, StaffuserRequiredMixin, UpdateView):
    model = Event
    template_name = "events/event_edit.html"
    fields = ['title', 'description', 'date', 'organizers']


class SendNotification(LoginRequiredMixin, StaffuserRequiredMixin, FormView):
    template_name = 'events/send_notification.html'
    form_class = NotificationForm
    success_url = '/'

    def form_valid(self, form):
        actor = self.request.user
        title = form.cleaned_data['verb']
        description = form.cleaned_data['description']
        to_events = form.cleaned_data['related_events']
        for event in to_events:
            users_to_notify = event.participants.filter(
                person_participations__status__in=[1, 2])
            for user in users_to_notify:
                notify.send(
                    actor, recipient=user, verb=title, target=event, description=description)
        return super(SendNotification, self).form_valid(form)


@require_POST
@login_required
@transaction.atomic
def participate(request):
    status_n = request.POST.get('status_n', None)
    event_pk = request.POST.get('event_pk', None)
    if status_n:
        event = get_object_or_404(Event, pk=event_pk)
        try:
            participation = Participation.objects.get(
                event=event, person=request.user)
            participation.status = status_n
            participation.save()
        except Participation.DoesNotExist:
            participation = Participation(
                event=event, person=request.user, status=status_n)
            participation.save()
        return HttpResponse()
    return HttpResponseBadRequest()


@require_GET
@login_required
@staff_member_required
def get_attendees(request):
    event_pk = request.GET.get('event_pk', None)
    if event_pk:
        event = get_object_or_404(Event, pk=event_pk)
        event_participants = event.participants.all()
        context = {}
        context['attendees_sure'] = list(event_participants.filter(
            person_participations__status=2).values('pk', 'username'))
        context['attendees_not_sure'] = list(event_participants.filter(
            person_participations__status=1).values('pk', 'username'))
        context['attendees_declined'] = list(event_participants.filter(
            person_participations__status=0).values('pk', 'username'))
        return JsonResponse(context)
    return HttpResponseBadRequest()

event system/event system/templates/events/event.html
extends "base.html" %}
{% block content %}
	<div class="row">
		<div data-event-pk='{{ event.pk }}' class="event">
			<h3><a href="{{ event.get_absolute_url }}" class="text-primary">{{ event.title }}</a></h3>
			<h5 class="text-muted">{{ event.location }}</h5>
			<p>{{ event.description|safe }}</p>
			{% with organizers=event.organizers.all %}
			{% if organizers %}
				<p>
					{% if organizers.count > 1 %}
						Organizers:
					{% else %}
						Organizer:
					{% endif %}
					{% for organizer in organizers %}
						<a href="{% url 'account_profile' organizer.pk organizer.username %}">{{ organizer.username }}</a>
						{% if not forloop.last %}
							,&nbsp;
						{% endif %}
					{% endfor %}
				</p>
				<p>
					{% if request.user.is_staff %}
						<a href="{% url 'events:event_edit' event.pk %}"><i class="glyphicon glyphicon-pencil text-muted pull-left">&nbsp;Edit</i></a>
					{% endif %}
				</p>
				<br />
			{% endif %}
		{% endwith %}
		{% if request.user.is_authenticated %}
		<div class="row">
			<div class="col-md-4 participation-statuses">
				<div class="btn-group btn-group-justified">
					{% for n, status in participation_statuses %}
						<a data-status='{{ n }}' class="btn btn-default p-status {% if user_status == n %}btn-primary{% endif %}">{{ status }}</a>
					{% endfor %}
				</div>
			</div>
		</div>
		{% endif %}
		<div class="row">
			<span class='st__large' displayText=''></span>
			<span class='st_facebook_large' displayText='Facebook'></span>
			<span class='st_twitter_large' displayText='Tweet'></span>
			<span class='st_email_large' displayText='E{% mail'></span>
		</div>
	</div>
	<div id="disqus_thread"></div>
</div>
{% endblock content %}

{% block additional_js %}
	<script type="text/javascript">var switchTo5x=true;</script>
	<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
	<script type="text/javascript">stLight.options({publisher: "d1ccfae5-2cf6-4b42-adbf-cf2fa059f90b", doNotHash: true, doNotCopy: false, hashAddressBar: false});</script>
	<script>
	/**
	*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
	*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
	*/
	/*
	var disqus_config = function () {
	this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
	this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
	};
	*/
	(function() {  // DON'T EDIT BELOW THIS LINE
	var d = document, s = d.createElement('script');
	
	s.src = '//eventsfossasia.disqus.com/embed.js';
	
	s.setAttribute('data-timestamp', +new Date());
	(d.head || d.body).appendChild(s);
	})();
	</script>
	<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
{% endblock additional_js %}

event system/event system/templates/events/event_create.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load i18n %}
{% load staticfiles %}
{% block additional_css %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
{% endblock additional_css %}
{% block content %}
	<div class="row">
		<form class="form" method="POST" action="" >
			{{ form.media }}
			{% csrf_token %}
			<div class="fieldWrapper">
				{{ form.title.label_tag }}
				{% bootstrap_field form.title show_label=False %}
				{{ form.title.errors }}
			</div>
			<div class="fieldWrapper">
				{{ form.description.label_tag }}
				{{ form.description }}
			</div>
			<div class="fieldWrapper">
				<label for="id_date">{{ form.date.label }}:</label>
				<div class="form-group">
					<label for="id_date" class="sr-only control-label">{{ form.date.label }}</label>
					<div class='input-group date' id='datetimepicker1'>
						<input type="text" title="" placeholder="Date" name="date" class="form-control">
						<span class="input-group-addon">
							<span class="glyphicon glyphicon-calendar"></span>
						</span>
					</div>
				</div>
				{{ form.date.errors }}
			</div>
			<div class="fieldWrapper">
				{{ form.organizers.label_tag }}
				{% bootstrap_field form.organizers show_label=False %}
				{{ form.organizers.errors }}
			</div>
			{% buttons %}
			<button class="btn btn-primary" type="submit" name="action">
			{% trans "Add" %}
			</button>
			{% endbuttons %}
	</form>
</div>
{% endblock content %}
{% block additional_js %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.0/moment.min.js"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript">
$(function () {
	$('#datetimepicker1').datetimepicker({
                 format: 'MM/DD/YYYY'
           });
});
</script>
{% endblock additional_js %}

event system/event system/templates/events/event_edit.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load i18n %}
{% load staticfiles %}
{% block additional_css %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
{% endblock additional_css %}
{% block content %}
	<div class="row">
		<form class="form" method="POST" action="" >
			{% csrf_token %}
			<div class="fieldWrapper">
				{{ form.title.label_tag }}
				{% bootstrap_field form.title show_label=False %}
				{{ form.title.errors }}
			</div>
			<div class="fieldWrapper">
				{{ form.description.label_tag }}
				{% bootstrap_field form.description show_label=False %}
			</div>
			<div class="fieldWrapper">
				<label for="id_date">{{ form.date.label }}:</label>
				<div class="form-group">
					<label for="id_date" class="sr-only control-label">{{ form.date.label }}</label>
					<div class='input-group date' id='datetimepicker1'>
						<input type="text" title="" placeholder="Date" name="date" class="form-control">
						<span class="input-group-addon">
							<span class="glyphicon glyphicon-calendar"></span>
						</span>
					</div>
				</div>
				{{ form.date.errors }}
			</div>
			<div class="fieldWrapper">
				{{ form.organizers.label_tag }}
				{% bootstrap_field form.organizers show_label=False %}
				{{ form.organizers.errors }}
			</div>
			{% buttons %}
			<button class="btn btn-primary" type="submit" name="action">
			{% trans "Add" %}
			</button>
		{% endbuttons %}
	</form>
</div>
{% endblock content %}
{% block additional_js %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.0/moment.min.js"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript">
$(function () {
	$('#datetimepicker1').datetimepicker({
                 format: 'MM/DD/YYYY'
           });
});
</script>
{% endblock additional_js %}

event system/event system/templates/events/events.html
{% extends "base.html" %}
{% block content %}
	<div class="row">
		{% for event in events %}
		<div class="event">
			<h3><a href="{{ event.get_absolute_url }}" class="text-primary">{{ event.title }}</a></h3>
			<h5 class="text-muted">{{ event.location }}</h5>
			<p>{{ event.description|truncatewords_html:100|safe }}</p>
			{% with organizers=event.organizers.all %}
			{% if organizers %}
				<p>
					{% if organizers.count > 1 %}
						Organizers:
					{% else %}
						Organizer:
					{% endif %}
					{% for organizer in organizers %}
						<a href="{% url 'account_profile' organizer.pk organizer.username %}">{{ organizer.username }}</a>
						{% if not forloop.last %}
							,&nbsp;
						{% endif %}
					{% endfor %}
				</p>
			{% endif %}
		{% endwith %}
		</div>
		{% if not forloop.last %}
			<hr/>
		{% endif %}
	{% endfor %}
	{% include "core/__items/pagination.html" %}
</div>
{% endblock content %}

event system/event system/templates/events/events_stats.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Event</th>
          <th>Date</th>
          <th>Accepted</th>
          <th>Are not sure</th>
          <th>Won't come</th>
        </tr>
      </thead>
      <tbody>
        {% for event in events %}
          <tr data-event-pk="{{ event.pk }}" data-toggle="collapse" data-target=".attendees{{ event.pk }}" class="attendees-open clickable">
            <td><a href="{{ event.get_absolute_url }}">{{ event.title|truncatewords:"4" }}</a></td>
            <td>{{ event.date }}</td>
            <td>{{ event.accepted }}</td>
            <td>{{ event.not_sure }}</td>
            <td>{{ event.declined }}</td>
          </tr>
          <tr class="table-accordion">
            <td></td>
            <td></td>
            <td class="attendees_sure{{ event.pk }}">
              <div class="collapse attendees{{ event.pk }}">
                <ul class="list-unstyled">
                </ul>
              </div>
            </td>
            <td class="attendees_not_sure{{ event.pk }}">
              <div class="collapse attendees{{ event.pk }}">
                <ul class="list-unstyled">
                </ul>
              </div>
            </td>
            <td class="attendees_declined{{ event.pk }}">
              <div class="collapse attendees{{ event.pk }}">
                <ul class="list-unstyled">
                </ul>
              </div>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock content %}

event system/event system/templates/events/send_notification.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load bootstrap3 %}

{% block content %}
</style>
	<div class="row">
		<form method="POST" action="">
			{% csrf_token %}
			{{ form.media }}
			{% bootstrap_form form %}
			{% buttons %}
				<button class="btn btn-primary" type="submit" name="action">
				{% trans "Send" %}
				</button>
			{% endbuttons %}
		</form>
	</div>
{% endblock content %}
{% block additional_js %}
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
{% endblock additional_js %}